version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: infini-synapse-mysql-prod
    restart: always
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "13306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置utf8字符集
    volumes:
      - ./__data/mysql/:/var/lib/mysql/ # ./__data/mysql/ 路径可以替换成自己的路径
      - ./deploy/sql/:/docker-entrypoint-initdb.d/ # 初始化的脚本，若 ./__data/mysql/ 文件夹存在数据，则不会执行初始化脚本
    networks:
      - infini_synapse_net

  infini-synapse:
    # build: 从当前路径构建镜像
    build:
      context: ./docker/infini-synapse/
    image: infinisynapse/infinisynapse:0.1.0
    container_name: infini-synapse-prod
    # pull_policy: always
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mysql
    volumes:
      - ./upload:/app/public/upload
      - ./datas/:/app/datas/
      - ./auto-coder/:/root/.auto-coder/
    networks:
      - infini_synapse_net

  infini-sql:
    # build: 从当前路径构建镜像
    build:
      context: ./docker/infini-sql/
    image: infinisynapse/infinisql:0.1.0
    container_name: infini-sql-prod
    ports:
      - "9003:9003"
    restart: always
    volumes:
      - ./upload:/app/public/upload
      - ./docker/infini-sql/app/logs/:/app/logs/
      - ./datas/:/app/datas/
      - ./auto-coder/:/root/.auto-coder/
    networks:
      - infini_synapse_net

networks:
  infini_synapse_net:
    name: infini_synapse_net
